name: Release
on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: kartverket/mapserver

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read

    outputs:
      version: ${{ steps.set_output.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,format=long

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build docker image and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      
      - name: Summarize Image Digest and Set Output
        id: set_output
        run: |
          echo "Full Image URL: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}@${{steps.build.outputs.digest}}" >> $GITHUB_STEP_SUMMARY
          echo "version=${{ github.ref_name }}@${{steps.build.outputs.digest}}" >> $GITHUB_OUTPUT